"""adding recipes and tags

Revision ID: 9e68aea6c797
Revises: de8312431ea7
Create Date: 2025-01-19 01:10:09.818648

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e68aea6c797"
down_revision: Union[str, None] = "de8312431ea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual Adjustment - Change schema to recipe_data in recipecategory enum so it doesn't go to the public schema
    op.create_table(
        "recipe_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="recipe_data",
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "description", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column(
            "ingredients", sa.String(length=1024), server_default="", nullable=False
        ),
        sa.Column(
            "instructions", sa.String(length=1024), server_default="", nullable=False
        ),
        sa.Column(
            "category",
            sa.Enum(
                "breakfast",
                "lunch",
                "dinner",
                "dessert",
                "snack",
                "drink",
                "other",
                name="recipecategory",
                schema="recipe_data",
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("rating", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "price_rating", sa.SmallInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "difficulty_rating", sa.SmallInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "prep_time_mins", sa.SmallInteger(), server_default="0", nullable=False
        ),
        sa.Column(
            "cook_time_mins", sa.SmallInteger(), server_default="0", nullable=False
        ),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("difficulty_rating <= 5"),
        sa.CheckConstraint("difficulty_rating >= 0"),
        sa.CheckConstraint("price_rating <= 5"),
        sa.CheckConstraint("price_rating >= 0"),
        sa.CheckConstraint("rating <= 5"),
        sa.CheckConstraint("rating >= 0"),
        sa.PrimaryKeyConstraint("id"),
        schema="recipe_data",
    )
    op.create_table(
        "recipe_tag_links",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe_data.recipes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["recipe_data.recipe_tags.id"],
        ),
        schema="recipe_data",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###\
    # Manual Adjustment - Added Drop command for recipecategory enum
    op.drop_table("recipe_tag_links", schema="recipe_data")
    op.drop_table("recipes", schema="recipe_data")
    op.drop_table("recipe_tags", schema="recipe_data")
    op.execute("DROP TYPE recipe_data.recipecategory;")
    # ### end Alembic commands ###
